language: python
python:
- '3.6'
install:
- pip install pytest
- pip install -e .
script:
- pytest
deploy:
  provider: pypi
  user: ngmarchant
  password:
    secure: DJcffo4XKkW7IrJsLAET/eMuJj0BuF3VSna0aYnVZAinsmZimSP5h3ZstT9WRM6/f5p3DONn8KpXlNfC7h8F1PrVXEXDUfldCfFjjP26aCjYK1XVeqD20OGwU2kEYbK+vAC3f7tp+s1HkmJ1dQGibjOb8v9MUsJP/57p6z/l/y7AHHm3NKKEuMre5y5HEIKjnMysZW4rEJ0KeC+M2SEObhXa1wbT+L8wdneaLW0xQedf3S4sHqoFWZb+E/6WImMjtpnwxBF8CHlY8kBRXu1WYWWj2lMDrK1QVNYd8ybCmOUwprInK3s2wvJrvlw8pPxwLuFeLlr2H+dkTG9tBLEBZ2SkCIZRaobVveNFx6MdX/AAsB3LZ2peunZ7wDcBsPtZ8GQCL2tBuSrYQV9f/mvRWRJqB3h0Zuqq8O2HGBHpAJ6TZtaSg5PQ0XFn/uC1aAJFz8X2QNhCHpbfrJNfBUcTEEB7Rh9xSfzaHHpmXqUUYisBYOKGElJt+XW5o5qw/BICwtqGGTo5pZtWNgt4V+zQ9tZnZfFRdJSONJyvVAuexasfcZfPAV7mxjTFNr73rk4G5oe0j+SvucAt0RmrCtpi66dTCbsjA7udo4tfdJ45epeHKmMzEp/37DyKd3U/D8gSDVdSfPBtU3T2Bw+9rAExjmgSKrHxKnu2k3gC7S7GJeM=
  on:
    tags: true
